# Generated by Django 5.0.6 on 2024-06-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinvetory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarInvetory',
            new_name='CarInventory',
        ),
    ]
