# Generated by Django 5.0.6 on 2024-06-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_carinvetory_carinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarInventory',
        ),
    ]
